name: .NET

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
          source-url: https://nuget.pkg.github.com/sirrandoo/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - run: dotnet build CommonLib.ExceptionParser/CommonLib.ExceptionParser.csproj
      - name: Create the package
        run: dotnet pack --configuration Release CommonLib.ExceptionParser/CommonLib.ExceptionParser.csproj
      - name: Publish the package to GPR
        run: dotnet nuget push CommonLib.ExceptionParser/bin/Release/*.nupkg
